client_encryption_options:
  enabled: true
  optional: false
  keystore: /certs/jks/keystore.jks
  keystore_password: changeit
  truststore: /certs/jks/truststore.jks
  truststore_password: changeit
  protocol: TLS
  algorithm: SunX509
  store_type: JKS
  cipher_suites: [TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA]

server_encryption_options:
  internode_encryption: none
